name: Bug Report
description: Create a report to help us fix an issue
title: '[Bug]'
labels: [Bug]
body:
  - type: dropdown
    id: data_attached
    attributes:
      label: "Data Files: Please add text files of the entity(s)."
      description: |
        Please add txt files of the entity(s). For txt files: Please go Developer Tools page -> Actions Tab -> Yaml Mode -> Run actions below
        Change start time, end time and sensor name
        
        **How to send text files**

        5minute data
        
        ```yaml
        action: recorder.get_statistics
        data:
          start_time: "2026-06-14 00:00:00"
          end_time: "2026-06-20 00:00:00"
          statistic_ids:
            - sensor.sandfilteranlage_laufzeit_heute
          period: 5minute
          types:
            - sum
            - change
            - last_reset
            - max
            - mean
            - min
            - state
        ```
        Hourly data
   
        ```yaml
        action: recorder.get_statistics
        data:
          start_time: "2026-06-14 00:00:00"
          end_time: "2026-06-20 00:00:00"
          statistic_ids:
            - sensor.your_sensor
          period: hour
          types:
            - sum
            - change
            - last_reset
            - max
            - mean
            - min
            - state
        ```
        Daily data
        
        ```yaml
        action: recorder.get_statistics
        data:
          start_time: "2026-06-14 00:00:00"
          end_time: "2026-06-20 00:00:00"
          statistic_ids:
            - sensor.sandfilteranlage_laufzeit_heute
          period: day
          types:
            - sum
            - change
            - last_reset
            - max
            - mean
            - min
            - state
        ```
        
      options:
        - "Added"
        - "I didn't"
    validations:
      required: true

  - type: textarea
    id: yaml_code
    attributes:
      label: "2. Your YAML Code"
      description: "Please paste your relevant YAML code in the area below. (The triple backticks are already provided, paste your code between them without breaking the format)."
      value: |
        ```yaml
        # Paste your yaml code here
        
        ```
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: "3. Bug Description"
      description: "Please provide the details of the issue or paste the exact error log you received below. (You can also drag and drop your CSV file here)."
    validations:
      required: true
