name: Bug Report
description: Create a report to help us fix an issue
title: ' '
labels: [Bug]
body:
  - type: dropdown
    id: lts_related
    attributes:
      label: "1. Is it related to Long Term Statistics (LTS)?"
      description: "⚠️ IF YOUR ANSWER IS 'YES': You must attach the CSV file for the related entities."
      options:
        - "No"
        - "Yes"
    validations:
      required: true

  - type: dropdown
    id: csv_attached
    attributes:
      label: "1a. If it is related to Long Term Statistics (LTS) then please attach your CSV file(s) of entities"
      description: "⚠️ ONLY attach data history (csv) if the bug is related to Long Term Statistics (LTS)."
      options:
        - "I did"
        - "I didn't"
    validations:
      required: true

  - type: textarea
    id: yaml_code
    attributes:
      label: "2. Your YAML Code"
      description: "Please paste your relevant YAML code in the area below. (The triple backticks are already provided, paste your code between them without breaking the format)."
      value: |
        ```yaml
        # Paste your yaml code here
        
        ```
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: "3. Bug Description"
      description: "Please provide the details of the issue or paste the exact error log you received below. (You can also drag and drop your CSV file here)."
    validations:
      required: true
