name: Bug Report
description: Create a report to help us fix an issue
title: '[Bug]'
labels: [Bug]
body:
  - type: dropdown
    id: csv_attached
    attributes:
      label: "CSV File"
      description: "Please add cvs file of the entity(s).  For csv file:  Please go your entity's more info dialog -> Click on Show More on the history line -> Select the related time period from the upper left corner -> Select Download Data from the upper right side menu"
      options:
        - "Added"
        - "I didn't"
    validations:
      required: true

  - type: textarea
    id: yaml_code
    attributes:
      label: "2. Your YAML Code"
      description: "Please paste your relevant YAML code in the area below. (The triple backticks are already provided, paste your code between them without breaking the format)."
      value: |
        ```yaml
        # Paste your yaml code here
        
        ```
    validations:
      required: true

  - type: textarea
    id: error_message
    attributes:
      label: "3. Bug Description"
      description: "Please provide the details of the issue or paste the exact error log you received below. (You can also drag and drop your CSV file here)."
    validations:
      required: true
